services:
  client_6_c:
    image: werty2648/traineetask6_client:v1
    ports:
        - "5111:8080"      
    volumes:
      - ./dp-keys/server:/app/keys 

  server_6_c:
    image: werty2648/traineetask6_server:v1
    ports:
    - "5123:8080"
    volumes:
      - ./dp-keys/server:/app/keys 
